print("hello")
#面向对象的解释型高级编程语言，强类型的动态脚本语言
#两个print不能写在同一行，syntax是语法错误
print(123)
print(123)
print(123)
print(123)
print(123)
print(123)
print(123)
print(123)
#debug中代码为蓝色的时候代表即将执行的代码，设置断点点击行数和本行代码左侧空白处
#总结：可以通过debug调试看到程序执行的顺序
"""
三引号实现多行注释
多行注释，可以是单引号也可以是双引号
快捷键：ctrl+/可以对选中文本添加注释或者取消注释
ctri+f查找
ctrl+d复制到下一行
"""
print("hhh","jjj","kkk",sep="\n")
#sep用来间隔多句话
#end是用来设定以...结尾，默认值是\n，可以切换为其它字符串
print(123,end=" ")
print(123)